db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./mysql_settings/my.cnf:/etc/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=111111
cache:
  image: redis
  ports:
    - "6379:6379"
  command: redis-server --appendonly yes
app:
  build: ./backends
  ports:
    - "8000:8000"
  volumes:
    - ./backends:/code
  links:
    - db
    - cache
  env_file: .env
  command: /usr/local/bin/gunicorn backends.wsgi:application -w 5 -b :8000
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  env_file: .env
  links:
    - app
