db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./mysql_settings/my.cnf:/etc/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=111111
cache:
  image: redis
  ports: 
    - "6379:6379"
  command: redis-server --appendonly yes
#warehouse:
#  build: ./warehouse
#  ports:
#    - "8000:8000"
#  volumes:
#    - ./warehouse:/code
#    - ./warehouse/warehouse/settings.py:/code/warehouse/settings.py
#  links:
#    - warehouse_db
#    - warehouse_cache
