# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('end', 'end')], default='waiting', max_length=255)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Activities_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'none'), (1, 'first'), (2, 'second'), (3, 'third')], default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.CharField(max_length=128)),
                ('exchange_link', models.CharField(max_length=128)),
                ('exchange_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('exchange_code', models.CharField(max_length=128)),
                ('thumbnail_path', models.CharField(max_length=128)),
                ('detail', models.TextField()),
                ('winner_cell', models.CharField(blank=True, max_length=20)),
                ('level', models.IntegerField(choices=[(0, 'none'), (1, 'first'), (2, 'second'), (3, 'third')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='warehouse.Activities')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='warehouse.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='activities_item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Brand'),
        ),
        migrations.AlterUniqueTogether(
            name='prizes',
            unique_together=set([('brand', 'exchange_code')]),
        ),
    ]
