# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20160112_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizes',
            name='activity',
        ),
        migrations.AddField(
            model_name='prizes',
            name='activity_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='warehouse.Activities_item'),
        ),
        migrations.AddField(
            model_name='prizes',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activities_item',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.Activities'),
        ),
    ]
