# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizes',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='warehouse.Activities'),
        ),
    ]
