# rules
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://localhost:5090"
    weight = 10
  [backends.backend2]
    [backends.backend2.circuitbreaker]
      expression = "ResponseCount() > 3"
      fallback = "http://localhost:5090/v1/over"
      fallbackDuration = 100000000
    [backends.backend2.servers.server1]
    url = "http://localhost:5090"
    weight = 1

[frontends]
  [frontends.frontend2]
  backend = "backend2"
  passHostHeader = true
    [frontends.frontend2.routes.test_2]
    rule = "Path"
    value = "/v1/tickets"
  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true
    [frontends.frontend1.routes.test_1]
    rule = "Host"
    value = "localhost"
  
